"use client";

import { useState } from "react";

interface SceneResult {
  start_time: number;
  end_time: number;
  overlay_text: string;
  description: string;
}

interface Narrative {
  strategy?: string;
  fears_exploited?: string[];
  desires_exploited?: string[];
  story_arc?: string;
  key_phrases?: { phrase: string; manipulation: string }[];
  voice_tone?: string;
}

interface ReportProps {
  streamUrl: string;
  scenes?: SceneResult[];
  breakdown?: string;
  primaryTechnique?: string;
  emotionalTriggers?: string[];
  cognitiveBiases?: string[];
  adArchetype?: string;
  targetAudience?: string;
  narrative?: Narrative | null;
  videoName?: string;
  youtubeUrl?: string;
  duration?: number;
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function buildMarkdown(report: ReportProps): string {
  const lines = [
    `# 🔬 Ad-Xray Report`,
    ``,
    `**Video:** ${report.videoName || "Untitled"}`,
    `**Source:** ${report.youtubeUrl || "—"}`,
    `**Duration:** ${report.duration ? `${Math.floor(report.duration)}s` : "—"}`,
    ``,
    `---`,
    ``,
  ];

  if (report.breakdown) {
    const bulletLines = report.breakdown
      .replace(/\n•\s/g, "\n- ")
      .replace(/^•\s/g, "- ")
      .split("\n")
      .map((l) => (l.startsWith("- ") ? l : `> ${l}`))
      .join("\n");
    lines.push(`## 📝 Psychological Breakdown`, ``, bulletLines, ``);
  }

  if (report.primaryTechnique) {
    lines.push(`## 🎯 Primary Technique`, ``, `**${report.primaryTechnique}**`, ``);
  }

  if (report.adArchetype) {
    lines.push(`**Archetype:** ${report.adArchetype}`, ``);
  }

  if (report.emotionalTriggers?.length) {
    lines.push(`### 😰 Emotional Triggers`, ``);
    report.emotionalTriggers.forEach((t) => lines.push(`- ${t}`));
    lines.push(``);
  }

  if (report.cognitiveBiases?.length) {
    lines.push(`### 🧠 Cognitive Biases`, ``);
    report.cognitiveBiases.forEach((b) => lines.push(`- ${b}`));
    lines.push(``);
  }

  if (report.narrative) {
    lines.push(`## 🗣️ Narrative Analysis`, ``);
    if (report.narrative.strategy) lines.push(`**Strategy:** ${report.narrative.strategy}`, ``);
    if (report.narrative.story_arc) lines.push(`**Story Arc:** ${report.narrative.story_arc}`, ``);
    if (report.narrative.voice_tone) lines.push(`**Voice Tone:** ${report.narrative.voice_tone}`, ``);
    if (report.narrative.key_phrases?.length) {
      report.narrative.key_phrases.forEach((kp) => lines.push(`- *"${kp.phrase}"* → ${kp.manipulation}`));
      lines.push(``);
    }
  }

  if (report.scenes?.length) {
    lines.push(`## ⏱️ Key Moments`, ``);
    report.scenes.forEach((s, i) => {
      lines.push(`### ${formatTime(s.start_time)} — ${s.overlay_text}`, ``);
      if (s.description) lines.push(`${s.description}`, ``);
    });
  }

  if (report.streamUrl) {
    lines.push(`---`, ``, `**Annotated Video:** ${report.streamUrl}`, ``);
  }

  lines.push(`*Generated by Ad-Xray — making the invisible visible.*`);
  return lines.join("\n");
}

export default function VideoPlayer(report: ReportProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const md = buildMarkdown(report);
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full max-w-5xl mx-auto space-y-10">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-xl font-light text-foreground">
            {report.videoName || "Ad Analysis"}
          </h2>
          {report.youtubeUrl && (
            <a
              href={report.youtubeUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-primary hover:underline font-mono"
            >
              {report.youtubeUrl}
            </a>
          )}
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 px-4 py-2 rounded-full bg-surface border border-border text-sm text-text-muted hover:text-foreground hover:border-primary/30 transition-all duration-200 cursor-pointer"
        >
          {copied ? (
            <>
              <svg className="w-4 h-4 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Copied
            </>
          ) : (
            <>
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-3-3v6m-7 4h14a1 1 0 001-1V7a1 1 0 00-1-1H5a1 1 0 00-1 1v11a1 1 0 001 1z" />
              </svg>
              Copy Report (Markdown)
            </>
          )}
        </button>
      </div>

      {report.streamUrl && (
        <div className="aspect-video rounded-card overflow-hidden bg-surface border border-border shadow-2xl">
          <video
            key={report.streamUrl}
            src={report.streamUrl}
            controls
            className="w-full h-full object-contain"
          />
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          {report.breakdown && (
            <section>
              <h3 className="text-sm font-mono text-primary uppercase tracking-wider mb-4">
                Psychological Breakdown
              </h3>
              <div className="prose prose-invert max-w-none text-text-muted leading-relaxed text-sm space-y-2">
                {report.breakdown.split(/\n•\s|\n- /).map((chunk, i) => {
                  if (i === 0) return <p key={i}>{chunk.replace(/^•\s?/, "")}</p>;
                  return (
                    <p key={i} className="flex gap-2">
                      <span className="text-primary flex-shrink-0">—</span>
                      <span>{chunk}</span>
                    </p>
                  );
                })}
              </div>
            </section>
          )}

          {report.narrative && (
            <section className="p-6 rounded-card bg-surface border border-border">
              <h3 className="text-sm font-mono text-primary uppercase tracking-wider mb-4">
                Narrative Manipulation
              </h3>
              {report.narrative.strategy && (
                <p className="text-sm text-text-muted mb-3">{report.narrative.strategy}</p>
              )}
              {report.narrative.story_arc && (
                <div className="flex items-center gap-2 text-xs font-mono text-primary bg-primary/5 rounded-subtle px-3 py-2 mb-4">
                  {report.narrative.story_arc}
                </div>
              )}
              {report.narrative.key_phrases && report.narrative.key_phrases.length > 0 && (
                <div className="space-y-2 mt-3">
                  {report.narrative.key_phrases.map((kp, i) => (
                    <div key={i} className="text-sm">
                      <span className="text-foreground font-medium">&ldquo;{kp.phrase}&rdquo;</span>
                      <span className="text-text-subtle"> — {kp.manipulation}</span>
                    </div>
                  ))}
                </div>
              )}
              {report.narrative.voice_tone && (
                <p className="text-xs text-text-subtle mt-3 italic">{report.narrative.voice_tone}</p>
              )}
            </section>
          )}
        </div>

        <div className="space-y-6">
          {report.primaryTechnique && (
            <div className="p-6 rounded-card bg-surface border border-primary/20">
              <span className="text-xs font-mono text-primary uppercase tracking-wider">Primary Technique</span>
              <p className="text-lg font-medium text-foreground mt-1">{report.primaryTechnique}</p>
              {report.adArchetype && (
                <p className="text-xs text-text-subtle mt-1">{report.adArchetype}</p>
              )}
            </div>
          )}

          {report.emotionalTriggers && report.emotionalTriggers.length > 0 && (
            <div className="p-6 rounded-card bg-surface border border-border">
              <span className="text-xs font-mono text-primary uppercase tracking-wider">Emotional Triggers</span>
              <div className="flex flex-wrap gap-1.5 mt-3">
                {report.emotionalTriggers.map((t) => (
                  <span key={t} className="text-xs px-2.5 py-1 rounded-full bg-primary/10 text-primary font-mono">
                    {t}
                  </span>
                ))}
              </div>
            </div>
          )}

          {report.cognitiveBiases && report.cognitiveBiases.length > 0 && (
            <div className="p-6 rounded-card bg-surface border border-border">
              <span className="text-xs font-mono text-primary uppercase tracking-wider">Cognitive Biases</span>
              <div className="flex flex-wrap gap-1.5 mt-3">
                {report.cognitiveBiases.map((b) => (
                  <span key={b} className="text-xs px-2.5 py-1 rounded-full bg-warning/10 text-warning font-mono">
                    {b}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {report.scenes && report.scenes.length > 0 && (
        <section>
          <h3 className="text-sm font-mono text-primary uppercase tracking-wider mb-4">
            Key Moments
          </h3>
          <div className="space-y-2">
            {report.scenes.map((scene, i) => (
              <div
                key={i}
                className="group flex items-start gap-4 p-4 rounded-card bg-surface border border-border hover:border-primary/30 transition-all duration-200"
              >
                <div className="flex-shrink-0 w-16 text-center">
                  <div className="text-xs font-mono text-primary">{formatTime(scene.start_time)}</div>
                </div>
                <div className="flex-1 min-w-0 space-y-1">
                  <p className="text-sm text-foreground font-medium">{scene.overlay_text}</p>
                  {scene.description && (
                    <p className="text-xs text-text-muted leading-relaxed">{scene.description}</p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
