"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";

interface SceneResult {
  start_time: number;
  end_time: number;
  overlay_text: string;
  description: string;
}

interface Narrative {
  strategy?: string;
  fears_exploited?: string[];
  desires_exploited?: string[];
  story_arc?: string;
  key_phrases?: { phrase: string; manipulation: string }[];
  voice_tone?: string;
}

interface DefenseStrategy {
  technique_targeted: string;
  strategy: string;
  question_to_ask: string;
}

interface ReportProps {
  streamUrl: string;
  scenes?: SceneResult[];
  breakdown?: string;
  primaryTechnique?: string;
  emotionalTriggers?: string[];
  cognitiveBiases?: string[];
  adArchetype?: string;
  targetAudience?: string;
  symbolsExploited?: string[];
  narrative?: Narrative | null;
  videoName?: string;
  youtubeUrl?: string;
  duration?: number;
  manipulationScore?: number;
  defenseStrategies?: DefenseStrategy[];
  empowermentMessage?: string;
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function buildMarkdown(report: ReportProps): string {
  const lines = [
    `# 🔬 Ad-Xray Report`,
    ``,
    `**Video:** ${report.videoName || "Untitled"}`,
    `**Source:** ${report.youtubeUrl || "—"}`,
    `**Duration:** ${report.duration ? `${Math.floor(report.duration)}s` : "—"}`,
  ];
  if (report.streamUrl) {
    lines.push(`**Annotated Video:** ${report.streamUrl}`, ``);
  }
  lines.push(``, `---`, ``);

  if (report.breakdown) {
    const bulletLines = report.breakdown
      .replace(/\n•\s/g, "\n- ")
      .replace(/^•\s/g, "- ")
      .split("\n")
      .map((l) => (l.startsWith("- ") ? l : `> ${l}`))
      .join("\n");
    lines.push(`## 📝 Psychological Breakdown`, ``, bulletLines, ``);
  }

  if (report.primaryTechnique) {
    lines.push(`## 🎯 Primary Technique`, ``, `**${report.primaryTechnique}**`, ``);
  }

  if (report.adArchetype) {
    lines.push(`**Archetype:** ${report.adArchetype}`, ``);
  }

  if (report.emotionalTriggers?.length) {
    lines.push(`### 😰 Emotional Triggers`, ``);
    report.emotionalTriggers.forEach((t) => lines.push(`- ${t}`));
    lines.push(``);
  }

  if (report.cognitiveBiases?.length) {
    lines.push(`### 🧠 Cognitive Biases`, ``);
    report.cognitiveBiases.forEach((b) => lines.push(`- ${b}`));
    lines.push(``);
  }

  if (report.symbolsExploited?.length) {
    lines.push(`### 🔣 Symbols Exploited`, ``);
    report.symbolsExploited.forEach((s) => lines.push(`- ${s}`));
    lines.push(``);
  }

  if (report.narrative) {
    lines.push(`## 🗣️ Narrative Analysis`, ``);
    if (report.narrative.strategy) lines.push(`**Strategy:** ${report.narrative.strategy}`, ``);
    if (report.narrative.story_arc) lines.push(`**Story Arc:** ${report.narrative.story_arc}`, ``);
    if (report.narrative.voice_tone) lines.push(`**Voice Tone:** ${report.narrative.voice_tone}`, ``);
    if (report.narrative.key_phrases?.length) {
      report.narrative.key_phrases.forEach((kp) => lines.push(`- *"${kp.phrase}"* → ${kp.manipulation}`));
      lines.push(``);
    }
  }

  if (report.scenes?.length) {
    lines.push(`## ⏱️ Key Moments`, ``);
    report.scenes.forEach((s, i) => {
      lines.push(`### ${formatTime(s.start_time)} — ${s.overlay_text}`, ``);
      if (s.description) lines.push(`${s.description}`, ``);
    });
  }

  lines.push(`*Generated by Ad-Xray — making the invisible visible.*`);
  return lines.join("\n");
}

export default function VideoPlayer(report: ReportProps) {
  const [copied, setCopied] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);

  const handleCopy = async () => {
    const md = buildMarkdown(report);
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyLink = async () => {
    if (report.streamUrl) {
      await navigator.clipboard.writeText(report.streamUrl);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2000);
    }
  };

  return (
    <>
      {report.manipulationScore && report.manipulationScore > 0 && (
        <div className="flex items-center justify-center mb-6">
          <div className={`flex items-center gap-3 px-6 py-3 rounded-full border ${
            report.manipulationScore >= 8 ? "bg-danger/10 border-danger/30" :
            report.manipulationScore >= 6 ? "bg-warning/10 border-warning/30" :
            "bg-success/10 border-success/30"
          }`}>
            <span className={`text-3xl font-light font-mono ${
              report.manipulationScore >= 8 ? "text-danger" :
              report.manipulationScore >= 6 ? "text-warning" :
              "text-success"
            }`}>{report.manipulationScore.toFixed(1)}</span>
            <div className="flex flex-col">
              <span className="text-[10px] font-mono uppercase tracking-widest text-text-subtle">Manipulation</span>
              <span className="text-[10px] font-mono uppercase tracking-widest text-text-subtle">Intensity /10</span>
            </div>
          </div>
        </div>
      )}
    <div className="w-full max-w-5xl mx-auto px-4 sm:px-0 sm:space-y-10 space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-xl font-light text-foreground">
            {report.videoName || "Ad Analysis"}
          </h2>
          {report.youtubeUrl && (
            <a
              href={report.youtubeUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-primary hover:underline font-mono"
            >
              {report.youtubeUrl}
            </a>
          )}
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 rounded-full bg-surface border border-border text-xs sm:text-sm text-text-muted hover:text-foreground hover:border-primary/30 transition-all duration-200 cursor-pointer"
          >
            {copied ? (
              <>
                <svg className="w-4 h-4 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                Copied
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth="1.5">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                Copy
              </>
            )}
          </button>
          {report.streamUrl && (
            <button
              onClick={handleCopyLink}
              className="flex items-center gap-2 px-4 py-2 rounded-full bg-surface border border-border text-xs sm:text-sm text-text-muted hover:text-foreground hover:border-primary/30 transition-all duration-200 cursor-pointer"
            >
              {linkCopied ? (
                <>
                  <svg className="w-4 h-4 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  Copied
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth="1.5">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
                  </svg>
                  Link
                </>
              )}
            </button>
          )}
        </div>
      </div>

      {report.streamUrl && (
        <div className="aspect-video rounded-card max-sm:rounded-none overflow-hidden bg-surface border border-border shadow-2xl">
          <video
            key={report.streamUrl}
            src={report.streamUrl}
            controls
            className="w-full h-full object-contain"
          />
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          {report.breakdown && (
            <section>
              <h3 className="text-sm font-mono text-primary uppercase tracking-wider mb-4">
                Psychological Breakdown
              </h3>
              <div className="prose prose-invert max-w-none text-text-muted text-sm">
                <ReactMarkdown>
                  {report.breakdown.replace(/^•\s/gm, "- ")}
                </ReactMarkdown>
              </div>
            </section>
          )}

          {report.narrative && (report.narrative.strategy || (report.narrative.key_phrases && report.narrative.key_phrases.length > 0)) && (
            <section className="p-6 rounded-card bg-surface border border-border">
              <h3 className="text-sm font-mono text-primary uppercase tracking-wider mb-4">
                Narrative Manipulation
              </h3>
              {report.narrative.strategy && (
                <p className="text-sm text-text-muted mb-3">{report.narrative.strategy}</p>
              )}
              {report.narrative.story_arc && (
                <div className="flex items-center gap-2 text-xs font-mono text-primary bg-primary/5 rounded-subtle px-3 py-2 mb-4">
                  {report.narrative.story_arc}
                </div>
              )}
              {report.narrative.key_phrases && report.narrative.key_phrases.length > 0 && (
                <div className="space-y-2 mt-3">
                  {report.narrative.key_phrases.map((kp, i) => (
                    <div key={i} className="text-sm">
                      <span className="text-foreground font-medium">&ldquo;{kp.phrase}&rdquo;</span>
                      <span className="text-text-subtle"> — {kp.manipulation}</span>
                    </div>
                  ))}
                </div>
              )}
              {report.narrative.voice_tone && (
                <p className="text-xs text-text-subtle mt-3 italic">{report.narrative.voice_tone}</p>
              )}
            </section>
          )}
        </div>

        <div className="space-y-6">
          {report.primaryTechnique && (
            <div className="p-6 rounded-card bg-surface border border-primary/20">
              <span className="text-xs font-mono text-primary uppercase tracking-wider">Primary Technique</span>
              <p className="text-lg font-medium text-foreground mt-1">{report.primaryTechnique}</p>
              {report.adArchetype && (
                <p className="text-xs text-text-subtle mt-1">{report.adArchetype}</p>
              )}
            </div>
          )}

          {report.emotionalTriggers && report.emotionalTriggers.length > 0 && (
            <div className="p-6 rounded-card bg-surface border border-border">
              <span className="text-xs font-mono text-primary uppercase tracking-wider">Emotional Triggers</span>
              <div className="flex flex-wrap gap-1.5 mt-3">
                {report.emotionalTriggers.map((t) => (
                  <span key={t} className="text-xs px-2.5 py-1 rounded-full bg-primary/10 text-primary font-mono">
                    {t}
                  </span>
                ))}
              </div>
            </div>
          )}

          {report.cognitiveBiases && report.cognitiveBiases.length > 0 && (
            <div className="p-6 rounded-card bg-surface border border-border">
              <span className="text-xs font-mono text-primary uppercase tracking-wider">Cognitive Biases</span>
              <div className="flex flex-wrap gap-1.5 mt-3">
                {report.cognitiveBiases.map((b) => (
                  <span key={b} className="text-xs px-2.5 py-1 rounded-full bg-warning/10 text-warning font-mono">
                    {b}
                  </span>
                ))}
              </div>
            </div>
          )}

          {report.symbolsExploited && report.symbolsExploited.length > 0 && (
            <div className="p-6 rounded-card bg-surface border border-border">
              <span className="text-xs font-mono text-primary uppercase tracking-wider">Symbols Exploited</span>
              <div className="flex flex-wrap gap-1.5 mt-3">
                {report.symbolsExploited.map((s) => (
                  <span key={s} className="text-xs px-2.5 py-1 rounded-full bg-subtle text-text-muted font-mono">
                    {s}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {report.scenes && report.scenes.length > 0 && (
        <section>
          <h3 className="text-sm font-mono text-primary uppercase tracking-wider mb-4">
            Key Moments
          </h3>
          <div className="space-y-2">
            {report.scenes.map((scene, i) => (
              <div
                key={i}
                className="group flex items-start gap-4 p-4 rounded-card bg-surface border border-border hover:border-primary/30 transition-all duration-200"
              >
                <div className="flex-shrink-0 w-12 sm:w-16 text-center">
                  <div className="text-xs font-mono text-primary">{formatTime(scene.start_time)}</div>
                </div>
                <div className="flex-1 min-w-0 space-y-1">
                  <p className="text-sm text-foreground font-medium">{scene.overlay_text}</p>
                  {scene.description && (
                    <p className="text-xs text-text-muted leading-relaxed">{scene.description}</p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {report.defenseStrategies && report.defenseStrategies.length > 0 && (
        <section>
          <h3 className="text-sm font-mono text-primary uppercase tracking-wider mb-4">
            How to Defend Yourself
          </h3>
          <div className="space-y-3">
            {report.defenseStrategies.map((ds, i) => (
              <div
                key={i}
                className="p-5 rounded-card bg-surface border border-border"
              >
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs font-mono text-primary/60">{String(i + 1).padStart(2, "0")}</span>
                  <span className="text-xs font-mono text-primary uppercase tracking-wider">
                    Countering: {ds.technique_targeted}
                  </span>
                </div>
                <p className="text-sm text-text-muted leading-relaxed mb-3">{ds.strategy}</p>
                <div className="flex items-start gap-2 text-sm">
                  <span className="text-warning flex-shrink-0 mt-0.5">?</span>
                  <span className="text-warning/80 italic">&ldquo;{ds.question_to_ask}&rdquo;</span>
                </div>
              </div>
            ))}
            {report.empowermentMessage && (
              <div className="mt-6 p-5 rounded-card bg-primary/5 border border-primary/20">
                <p className="text-sm text-text-muted leading-relaxed italic">
                  {report.empowermentMessage}
                </p>
              </div>
            )}
          </div>
        </section>
      )}
    </div>
    </>
  );
}
